repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.0
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.12.0-2
  hooks:
    - id: shfmt
- repo: local
  hooks:
    - id: cargo-fmt
      name: cargo fmt
      entry: cargo fmt --manifest-path mcts/Cargo.toml
      language: system
      pass_filenames: false
    - id: cargo-check
      name: cargo check
      entry: cargo check --manifest-path mcts/Cargo.toml
      language: system
      pass_filenames: false
    - id: cargo-test
      name: cargo test
      entry: cargo test --manifest-path mcts/Cargo.toml
      language: system
      pass_filenames: false
    - id: maturin-develop
      name: maturin develop
      entry: maturin develop
      language: system
      pass_filenames: false
