[build-system]
requires = ["maturin"]
build-backend = "maturin"

[project]
name = "go-zero-mcts-rs"
dependencies = [
    "numpy",
    "numba",
    "pandas",
    "sgfmill",
    "requests",
    "safetensors",
    "torch",
    "wandb",
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: implementation :: CPython",
    "Programming Language :: Python :: implementation :: PyPy",
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "go_zero_mcts_rs"
manifest-path = "mcts_rs/Cargo.toml"
