[package]
name = "go_zero_mcts_rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "go_zero_mcts_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
numpy = "0.25.0"
rand = "0.9.2"
rand_distr = "0.5.1"
dashmap = "6.1.0"
